---
title: "Untitled"
output: html_document
date: "2025-08-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Controlando Números e Janelas Gráficas

```{r}
x=c(1,2,3,4,5)
par(mfrow=c(1,3))
barplot(x,ylim = c(0,30))
barplot(x^2,ylim = c(0,30))
barplot(x^3,ylim = c(0,30))


par(mar=c(8,3,4,2))
barplot(x,names=c("AA","BB","CC","DD","EE"),cex.names=1.25,las=3,bg="lightblue",border = NA,col="blue3")

```

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r, eval=FALSE}
x=c(1,2,3)


par(mar=c(8,3,4,2), bg="#FF6666")
barplot(x,names=c("AA","BB","CC"),ylab="values",cex.names=1.25,las=3,border = NA,col="blue3",horiz = T)




```

| t1  | t2  |
|:---:|:---:|
| 10  | 20  |
| 30  | 40  |

------------------------------------------------------------------------

[//] comentário
